name: Release Foundry VTT Module

on:
  workflow_dispatch:

  # push:
  #   branches: [main]

  # pull_request:
  #   branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0

      - name: Get version
          id: version
          uses: notiz-dev/github-action-json-property@release
          with: 
              path: 'module.json'
              prop_path: 'version'

      - run: echo ${{ steps.version.outputs.prop }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: contains(steps.version.outputs.prop, '-')
          draft: true
          tag_name: v${{ steps.version.outputs.prop }}
