name: Release Foundry VTT Module

on:
  workflow_dispatch:

  push:
    branches: [main]

  # pull_request:
  #   branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'

      - name: Get version from module.json
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'module.json'
          prop_path: 'version'

      - name: Set versions variables
        id: versions
        run: |
          previous="${{ steps.previoustag.outputs.tag }}"
          current="v${{ steps.version.outputs.prop }}"
          echo "::set-output name=previous::$previous"
          echo "::set-output name=current::$current"

      - name: Output values
        run: |
          echo "Previous: ${{ steps.versions.outputs.previous }}"
          echo "Current: ${{ steps.versions.outputs.current }}"
          echo "Should release? ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}"

      - run: zip -r ./module.zip main.js module.json LICENSE css/ lang/
        if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

      - name: Update module release download url
        uses: jossef/action-set-json-field@v2
        with:
          file: module.json
          field: download
          value: https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.prop }}/module.zip
        if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

      - name: Create the GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.prop }}
          files: |
            module.zip
            module.json
        if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}
