name: Release Foundry VTT Module

on:
  push:
    branches: [main]

  # pull_request:
  #   branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setCommonVars: true
          setAllVars: true

      # - name: Gets semantic release info
      #   id: semantic_release_info
      #   uses: jossef/action-semantic-release-info@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

      - run: |
          echo 'NpmPackageVersion: ${{ steps.nbgv.outputs.NpmPackageVersion }}'

      - name: Update module.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: module.json
          field: version
          value: ${{ steps.nbgv.outputs.NpmPackageVersion }}

      # - uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ steps.nbgv.outputs.NpmPackageVersion }}
      #     release_name: v${{ steps.nbgv.outputs.NpmPackageVersion }} Release
      #     draft: true
      #     prerelease: true
      #   # if: github.event_name == 'push'

      - name: Release
        id: gh-release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          tag_name: v${{ steps.nbgv.outputs.NpmPackageVersion }}
          files: |
            **/*.*

      - run: |
          echo 'upload_url: ${{ steps.gh-release.outputs.upload_url }}'
