name: Release Foundry VTT Module

on:
  workflow_dispatch:

  # push:
  #   branches: [main]

  # pull_request:
  #   branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version from module.json
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'module.json'
          prop_path: 'version'

      - name: Create the GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.prop }}
